import { 
  Student, 
  Attendance, 
  FeeCategory, 
  FeeStructure, 
  Payment, 
  LibraryBook, 
  BookIssue, 
  Seat, 
  Locker, 
  DashboardStats,
  Alert 
} from '@/types';

// Mock Students Data
export const mockStudents: Student[] = [
  {
    id: '1',
    enrollmentNumber: 'STU001',
    name: 'Amit Kumar',
    class: '10th',
    batch: '2024-25',
    guardianName: 'Rajesh Kumar',
    guardianPhone: '+91 9876543210',
    phone: '+91 9876543211',
    email: 'amit.kumar@email.com',
    shift: 'morning',
    seatNumber: 'A01',
    lockerAssigned: 'L001',
    status: 'active',
    dateOfJoining: '2024-04-01',
    address: '123 Main Street, Delhi',
    emergencyContact: '+91 9876543212',
  },
  {
    id: '2',
    enrollmentNumber: 'STU002',
    name: 'Priya Sharma',
    class: '11th',
    batch: '2024-25',
    guardianName: 'Suresh Sharma',
    guardianPhone: '+91 9876543213',
    phone: '+91 9876543214',
    email: 'priya.sharma@email.com',
    shift: 'evening',
    seatNumber: 'B15',
    lockerAssigned: 'L002',
    status: 'active',
    dateOfJoining: '2024-04-01',
    address: '456 Oak Avenue, Mumbai',
    emergencyContact: '+91 9876543215',
  },
  {
    id: '3',
    enrollmentNumber: 'STU003',
    name: 'Rahul Gupta',
    class: '12th',
    batch: '2024-25',
    guardianName: 'Mukesh Gupta',
    guardianPhone: '+91 9876543216',
    phone: '+91 9876543217',
    shift: 'morning',
    seatNumber: 'C08',
    status: 'active',
    dateOfJoining: '2024-04-01',
    address: '789 Pine Road, Bangalore',
    emergencyContact: '+91 9876543218',
  },
];

// Mock Attendance Data
export const mockAttendance: Attendance[] = [
  {
    id: '1',
    studentId: '1',
    student: mockStudents[0],
    date: '2025-12-13',
    morningPresent: true,
    eveningPresent: true,
    markedBy: '1',
    markedAt: '2025-12-13T09:00:00Z',
  },
  {
    id: '2',
    studentId: '2',
    student: mockStudents[1],
    date: '2025-12-13',
    morningPresent: false,
    eveningPresent: true,
    markedBy: '1',
    markedAt: '2025-12-13T14:00:00Z',
  },
];

// Mock Fee Categories
export const mockFeeCategories: FeeCategory[] = [
  {
    id: '1',
    name: 'Tuition Fee',
    description: 'Monthly tuition fee',
    amount: 5000,
    isRecurring: true,
    dueDay: 5,
  },
  {
    id: '2',
    name: 'Library Fee',
    description: 'Annual library membership',
    amount: 1000,
    isRecurring: false,
    dueDay: 0,
  },
  {
    id: '3',
    name: 'Transport Fee',
    description: 'Monthly transportation',
    amount: 2000,
    isRecurring: true,
    dueDay: 10,
  },
];

// Mock Fee Structures
export const mockFeeStructures: FeeStructure[] = [
  {
    id: '1',
    studentId: '1',
    student: mockStudents[0],
    categoryId: '1',
    category: mockFeeCategories[0],
    amount: 5000,
    dueDate: '2025-12-05',
    status: 'paid',
    paidAmount: 5000,
    remainingAmount: 0,
  },
  {
    id: '2',
    studentId: '2',
    student: mockStudents[1],
    categoryId: '1',
    category: mockFeeCategories[0],
    amount: 5000,
    dueDate: '2025-12-05',
    status: 'pending',
    paidAmount: 0,
    remainingAmount: 5000,
  },
  {
    id: '3',
    studentId: '3',
    student: mockStudents[2],
    categoryId: '2',
    category: mockFeeCategories[1],
    amount: 1000,
    dueDate: '2025-12-10',
    status: 'overdue',
    paidAmount: 0,
    remainingAmount: 1000,
  },
  {
    id: '4',
    studentId: '1',
    student: mockStudents[0],
    categoryId: '3',
    category: mockFeeCategories[2],
    amount: 2000,
    dueDate: '2025-12-15',
    status: 'partial',
    paidAmount: 1000,
    remainingAmount: 1000,
  },
];

// Mock Library Books
export const mockLibraryBooks: LibraryBook[] = [
  {
    id: '1',
    title: 'Mathematics Grade 10',
    author: 'Dr. R.D. Sharma',
    isbn: '978-9351419382',
    edition: '2023',
    publisher: 'Dhanpat Rai Publications',
    category: 'Mathematics',
    totalCopies: 25,
    availableCopies: 18,
    purchaseDate: '2024-03-15',
    price: 450,
    description: 'Complete mathematics textbook for class 10',
  },
  {
    id: '2',
    title: 'Physics Concepts',
    author: 'HC Verma',
    isbn: '978-8177091874',
    edition: '2022',
    publisher: 'Bharati Bhawan',
    category: 'Physics',
    totalCopies: 20,
    availableCopies: 15,
    purchaseDate: '2024-03-20',
    price: 380,
    description: 'Advanced physics concepts for competitive exams',
  },
  {
    id: '3',
    title: 'Chemistry Fundamentals',
    author: 'OP Tandon',
    isbn: '978-9386873513',
    edition: '2023',
    publisher: 'GRB Bathla & Sons',
    category: 'Chemistry',
    totalCopies: 18,
    availableCopies: 12,
    purchaseDate: '2024-03-25',
    price: 420,
    description: 'Comprehensive chemistry textbook',
  },
];

// Mock Book Issues
export const mockBookIssues: BookIssue[] = [
  {
    id: '1',
    bookId: '1',
    book: mockLibraryBooks[0],
    studentId: '1',
    student: mockStudents[0],
    issueDate: '2025-12-01',
    dueDate: '2025-12-15',
    returnDate: '2025-12-10',
    fineAmount: 0,
    status: 'returned',
    issuedBy: '3',
    returnedBy: '3',
  },
  {
    id: '2',
    bookId: '2',
    book: mockLibraryBooks[1],
    studentId: '2',
    student: mockStudents[1],
    issueDate: '2025-12-05',
    dueDate: '2025-12-19',
    fineAmount: 25,
    status: 'overdue',
    issuedBy: '3',
  },
];

// Mock Seats
export const mockSeats: Seat[] = [
  {
    id: '1',
    seatNumber: 'A01',
    room: 'Room 101',
    section: 'Section A',
    hasLocker: true,
    isOccupied: true,
    occupiedBy: '1',
    student: mockStudents[0],
    status: 'occupied',
    lastModified: '2025-12-13T10:00:00Z',
  },
  {
    id: '2',
    seatNumber: 'A02',
    room: 'Room 101',
    section: 'Section A',
    hasLocker: false,
    isOccupied: false,
    status: 'available',
    lastModified: '2025-12-13T10:00:00Z',
  },
  {
    id: '3',
    seatNumber: 'B15',
    room: 'Room 102',
    section: 'Section B',
    hasLocker: true,
    isOccupied: true,
    occupiedBy: '2',
    student: mockStudents[1],
    status: 'occupied',
    lastModified: '2025-12-13T14:00:00Z',
  },
];

// Mock Lockers
export const mockLockers: Locker[] = [
  {
    id: '1',
    lockerNumber: 'L001',
    linkedSeatId: '1',
    seat: mockSeats[0],
    assignedStudentId: '1',
    student: mockStudents[0],
    isAssigned: true,
    accessLog: [],
  },
  {
    id: '2',
    lockerNumber: 'L002',
    linkedSeatId: '3',
    seat: mockSeats[2],
    assignedStudentId: '2',
    student: mockStudents[1],
    isAssigned: true,
    accessLog: [],
  },
];

// Mock Dashboard Stats
export const mockDashboardStats: DashboardStats = {
  totalStudents: 1250,
  newAdmissions: 45,
  studentsLeft: 8,
  morningShiftCount: 680,
  eveningShiftCount: 570,
  totalFeesCollected: 1250000,
  pendingFees: 87500,
  advancePayments: 12500,
  libraryExpenses: {
    monthly: 25000,
    total: 275000,
  },
  overdueBooks: 12,
  pendingFeesCount: 35,
  booksIssuedToday: 45,
  seatsOccupied: 280,
  lockersAssigned: 150,
  lockerTotal: 200,
  seatTotal: 300,
};

// Mock Alerts
export const mockAlerts: Alert[] = [
  {
    id: '1',
    type: 'overdue_books',
    title: 'Overdue Books',
    message: '12 books are overdue for return',
    severity: 'high',
    createdAt: '2025-12-13T09:00:00Z',
    isRead: false,
    actionUrl: '/library/overdue',
  },
  {
    id: '2',
    type: 'pending_fees',
    title: 'Pending Fees',
    message: '35 students have pending fee payments',
    severity: 'medium',
    createdAt: '2025-12-13T08:30:00Z',
    isRead: false,
    actionUrl: '/fees/pending',
  },
  {
    id: '3',
    type: 'low_attendance',
    title: 'Low Attendance Alert',
    message: '8 students have attendance below 75%',
    severity: 'medium',
    createdAt: '2025-12-12T16:00:00Z',
    isRead: true,
    actionUrl: '/attendance/reports',
  },
];

// Mock Payments
export const mockPayments: Payment[] = [
  {
    id: '1',
    studentId: '1',
    feeStructureId: '1',
    amount: 5000,
    paymentDate: '2025-12-02',
    paymentMethod: 'online',
    receiptNumber: 'REC001',
    notes: 'Tuition fee for December 2025',
    receivedBy: '2',
  },
];